matrix_width: 48
matrix_height: 32
num_panels: 5
wled_host: 10.0.0.2
wled_timeout: 0.5
led_protocol: E1.31
wiring_mode: THREE_PANEL_COL_MAJOR
frame_rate: 30
cycle_beats: 4
auto_bpm: true
brightness: 0.36
mic_sensitivity: 1.72
